#!/data/data/com.termux/files/usr/bin/bash

# Auto Install Tools <3
# Coded by Mrh1l4n9

# Bersihkan Layar
clear

#This colour
green='\e[0;34m'
white='\e[1;37m'

# Isi co <3
echo -e $green" 01) SQLMap
echo -e $green" 02) Dirbuster
echo -e $white" 03) exit
echo -e $white""
read -p "[Mrh1l4n9@Tools]" act;

if [ $act = 1 ] || [ $act = 01 ]
then
clear
echo -e $green" Installing SQLMap "
sleep 1
apt update && apt upgrade
apt install python2
git clone https://github.com/sqlmapproject/sqlmap.git
cd ~/
echo -e $green" T E R I N T S T A L L "
fi

if [ $act = 2 ] || [ $act = 02 ]
then
clear
echo -e $green" Installing Dirbuster "
sleep 1
apt update && apt upgrade
apt install python''
git clone https://github.com/maurosoria/dirsearch.git
cd ~/
echo -e $green" T E R I N S T A L L "
fi

if [ $act = 3 ] || [ $act = 03 ]
then
echo -e "Terimakasih"
sleep 1
echo -e "Jangan banyak bacot"
sleep 1
exit
fi
